version: "3"
services:
  application:
    image: spring-boot-mysql-app
    ports:
      - "8081:8081"
    networks:
      - springboot-db-net
    depends_on:
      - mysqldb
    
  mysqldb:
    image: mysql:8.0
    networks:
      - springboot-db-net
    environment:
      - MYSQL_ROOT_PASSWORD=Pthakare@27
      - MYSQL_DATABASE=employeedetail
networks:
  springboot-db-net: